### ISSUE TITLE
How to get AST, CFG graph

### ISSUE THREAD

**Issue by shangqing-liu** [ShiftLeftSecurity/joern#10]
Hi, may I ask how can I get AST, CFG graph with this tool. We can just use the simple interfaces supplied by queryprimitives.

**Comment by fabsx00** [comment]
Hi,
the docs here tell you how to query the graph: https://joern.io/docs/querying/
The CPG contains a complete control flow graph, simply follow the CFG edges. Expressions/Statements also form abstract syntax trees.

**Comment by fabsx00** [comment]
Closed as duplicate of https://github.com/ShiftLeftSecurity/codepropertygraph/issues/129
