### ISSUE TITLE
Fail to run test case

### ISSUE THREAD

**Issue by verazuo** [ShiftLeftSecurity/joern#110]
Hi, after successful building joern by `sbt stage`, I tried to follow the [quickstart](https://joern.io/docs/essentials/quickstart/) but get following result. 
```
(py36) ➜  joern git(master):  ./joern-parse  joern-cli/src/test/resources/testcode/free
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
You need to run 'sbt stage' first
```

It looks like it cannot recognize the following parameter is a dirname, however when I tried following command, it still didn't work.
```
./joern-parse  joern-cli/src/test/resources/testcode/free/free.c
```
I run this command in `joern` dir, which absolutely contains the two files.

Does anyone have ideas about this situation? Thx!

**Comment by verazuo** [comment]
Found out the solution.

It is because of the wrong path setting in `joern-parse` at line 5 and line 7.
```
SCRIPT="$SCRIPT_ABS_DIR/joern-server/target/universal/stage/bin/joern-server"

LOG4J_FILENAME="$SCRIPT_ABS_DIR/joern-cli/src/main/resources/log4j2.xml"
```

After changing it to 
```
SCRIPT="joern-server/target/universal/stage/bin/joern-server"

LOG4J_FILENAME="joern-cli/src/main/resources/log4j2.xml"
```

It successful runs and output the `cpg.bin.zip`

BTW, the path in `joernd` contains the same issue.

**Comment by fabsx00** [comment]
Can you make a PR?

**Comment by verazuo** [comment]
Absolutely! And here we go~ [#111](https://github.com/ShiftLeftSecurity/joern/pull/111)
