### ISSUE TITLE
Support Scala Native

### ISSUE THREAD

**Issue by XVilka** [ShiftLeftSecurity/joern#112]
To keep the voracious JVM in the cage.

[Scala Native](http://scala-native.org/) is an optimizing ahead-of-time compiler and lightweight managed runtime designed specifically for Scala. It features:
- Low-level primitives.
- Seamless interop with native code.
- Instant startup time.

They are working on the upcoming [0.4.0 release](https://github.com/scala-native/scala-native/milestone/21) right now.

**Comment by hubertp** [comment]
atm Scala Native is a bit too bleeding edge for us to support/move to. We would also have to generate Scala Native artifacts for all our dependencies.
If statups/memory become an issue then a much quicker win would be to play with Graal's SubstrateVM.
