### ISSUE TITLE
Scripts for AST, CFG, and PDG extraction

### ISSUE THREAD

**Issue by fabsx00** [ShiftLeftSecurity/joern#114]
Let's create scripts that will extract ASTs, CFGs, and PDGs for all functions and write them to a file. This will enable the research community to use Joern as a tool for the extraction of graph-based intermediate program representations via the fuzzy parser.

**Comment by conikeec** [comment]
@fabsx00 can we create it here https://github.com/ShiftLeftSecurity/scripts in the `C` folder please

**Comment by fabsx00** [comment]
I guess we are going to need a public version of that for public scripts ;)

**Comment by fabsx00** [comment]
Related: https://github.com/ShiftLeftSecurity/joern/issues/114 - we will want to also just allow exporting of the entire graph per method. What we're looking at here is a graph exporter tool.

**Comment by max-leuthaeuser** [comment]
This should be done now with PR #135, #142, #147, and #153.
