### ISSUE TITLE
Installation script

### ISSUE THREAD

**Issue by fabsx00** [ShiftLeftSecurity/joern#117]
Currently, joern is simply unzipped and used from the target directory, as many people do for other JVM-based programs such as IntelliJ and Burp Suite. It would be cleaner though to have an installer that allows us to place joern programs in the path. This will then only simplify packaging for distros.

**Comment by fabsx00** [comment]
Install script for source version: https://github.com/ShiftLeftSecurity/joern/pull/161 - we might want to also add one for binary releases later.

**Comment by GlassAndOneHalf** [comment]
Done in https://github.com/ShiftLeftSecurity/joern/pull/162/files
