### ISSUE TITLE
Remove `joern-query`

### ISSUE THREAD

**Issue by fabsx00** [ShiftLeftSecurity/joern#119]
Since we now have the ammonite-based Joern shell, we no longer require `joern-query` as the same can be achieved via
```
loadCpg(...); $query
````
I would suggest we remove `joern-query` and all references to it in the documentation. Opinions?

**Comment by GlassAndOneHalf** [comment]
I agree - a user can now invoke the Ammonite shell and pass the `script` option if they need to do any scripting.
