### ISSUE TITLE
Support for PHP Extension

### ISSUE THREAD

**Issue by silverfoxy** [ShiftLeftSecurity/joern#132]
The previous version of joern (https://github.com/octopus-platform/joern/tree/dev/projects/extensions/joern-php) looks to have the ability to ingest PHP ast and populate its database, I was wondering if the same thing is possible with currently supported branch of joern or if I should be using the previous version for that feature?

**Comment by fabsx00** [comment]
PHP support has not yet been ported over, so, if you need it, you'll have to go with the old version for now.
