### ISSUE TITLE
`runScript(filename)` should check if CPG is already loaded

### ISSUE THREAD

**Issue by fabsx00** [ShiftLeftSecurity/joern#174]
Looks like `run(filename)` (without the `cpg` parameter) loads `cpg.bin.zip` by deafult. This can be quite slow for large graphs. Can we check if a graph is already loaded and use that if so?

**Comment by GlassAndOneHalf** [comment]
As discussed with @fabsx00  remove the standalone `runScript(filename)` and instead add an extension to `Cpg` that allows something along the lines of `cpg.runScript(filename)` that translates to `runScript(filename, cpg)`

**Comment by GlassAndOneHalf** [comment]
Resolved in https://github.com/ShiftLeftSecurity/joern/pull/180
