### ISSUE TITLE
Automatically run `~/.joern/predef.sc` on startup

### ISSUE THREAD

**Issue by fabsx00** [ShiftLeftSecurity/joern#176]
Since some of the code between the Joern and Ocular shell are shared, we end up picking up the startup file `predef.sc` in ~/.shiftleft/ocular. That's fine, but we should also pick up ~/.joern/predef.sc.

**Comment by fabsx00** [comment]
This seems to be where that path is defined: https://github.com/ShiftLeftSecurity/codepropertygraph/blob/master/console/src/main/scala/io/shiftleft/console/StorageBackend.scala#L16
Ammonite then executes predef.scala, I think.

**Comment by GlassAndOneHalf** [comment]
Initial work to enable this: https://github.com/ShiftLeftSecurity/codepropertygraph/pull/488

**Comment by GlassAndOneHalf** [comment]
Fixed to read from `~/.shiftleft/joern` in https://github.com/ShiftLeftSecurity/joern/pull/185
