### ISSUE TITLE
Error after reproducing kernel examples from joern documentation

### ISSUE THREAD

**Issue by dukebarman** [ShiftLeftSecurity/joern#182]
I've tried to reproduce kernel examples with joern (https://joern.io/docs/kernelexamples/):

```
# ./joern-parse ~/linux/drivers/scsi/aacraid/
# ./joern
joern> loadCpg("cpg.bin.zip")
... # commands from documentation
joern> println(sinkArguments.reachableByFlows(cpg.identifier).l.size)
559 # Another number than in docs, maybe it's not an error
... # commands from documentation
joern> reachingDefs1.intersect(reachingDefs2).foreach(elem => println(elem.code))
java.lang.ClassCastException: io.shiftleft.codepropertygraph.generated.nodes.Call cannot be cast to io.shiftleft.codepropertygraph.generated.nodes.Identifier
  scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:321)
  scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:977)
  scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:977)
  ammonite.$sess.cmd8$.<init>(cmd8.sc:1)
  ammonite.$sess.cmd8$.<clinit>(cmd8.sc)
```

**Comment by GlassAndOneHalf** [comment]
Hi @dukebarman - which version of Joern are you using?

I get `1069` entries compared to your `559` and the `302` in the docs.

Running the second command, I get the same error you - but I'm able to work around this by inserting a cast:
`reachingDefs1.intersect(reachingDefs2).asInstanceOf[Set[Call]].foreach(e => println(e.code)) `

**Comment by GlassAndOneHalf** [comment]
After some more investigation it seems that the `reachableBy` definition was updated after these docs were written to preserve type information (Commit in shiftleftsecurity/codepropertygraph@ dc4d995e3206d1c5d19d7d53569be10cd31c56b6 ).

I'll update the documentation to include this cast. Thanks for the report!

**Comment by GlassAndOneHalf** [comment]
See https://github.com/ShiftLeftSecurity/joern/pull/183

**Comment by dukebarman** [comment]
I redownload last version of joern-cli. Thanks! New queries works. But I have 559 entries yet. And after last query I have another numbers:
```
cfu2.asInstanceOf[Set[Call]].foreach(elem => println(elem.code, elem.lineNumber.get))
(kfib = fibptr->hw_fib_va,77)
(aac_fib_alloc(dev),72)
(fibptr = aac_fib_alloc(dev),72)
```
Maybe you didn't make checkout to 4.7 linux version?

**Comment by GlassAndOneHalf** [comment]
You're right! I've updated the docs again in this PR to reflect the results when parsing the 4.7 kernel. See https://github.com/ShiftLeftSecurity/joern/pull/185
