### ISSUE TITLE
Exception: Invalid request: <Response [400]>

### ISSUE THREAD

**Issue by Smile-zjk** [ShiftLeftSecurity/joern#187]
I follow the Importing Code part in the Joern Documentation, but when I try to create Code CPG with cpg-create, the following problems were encountered,''Exception: Invalid request: <Response [400]>''.

I follow the Document step by step, and  I don't know what's wrong with it, I would appreciate it if you could help me out

![image](https://user-images.githubusercontent.com/41987902/69113817-107ed400-0abf-11ea-9d4c-e973de6294ac.png)
![image](https://user-images.githubusercontent.com/41987902/69113838-1c6a9600-0abf-11ea-9002-e25dfc2de71a.png)

**Comment by GlassAndOneHalf** [comment]
Hi @Smile-zjk - when running `cpg-create` you need to specify the path to the source folder relative to the server's current working directory. In your case, the server's working directory is `~/joern-server`.

As you are running `cpg-create` from `~` you need to run it with `cpg-create ../tarpit-c`. This is slightly unintuitive - however we could investigate implementing an API that allows you to upload a CPG to the server which should help.

I will update the Joern documentation to clarify this - apologies for the confusion!

**Comment by GlassAndOneHalf** [comment]
See https://github.com/ShiftLeftSecurity/joern/pull/188 for the update.

If you need further help please create a new issue or hop on over to our [gitter](https://gitter.im/joern-code-analyzer/community) channel.

**Comment by Smile-zjk** [comment]
Thank you very much for your reply, the problem has been solved.
