### ISSUE TITLE
Support installation via script on macOS

### ISSUE THREAD

**Issue by l0s** [ShiftLeftSecurity/joern#229]
Attempting to run the `joern-install.sh` script on macOS produces the following error:

    readlink: illegal option -- f
    usage: readlink [-n] [file ...]

System information:

    sh-3.2$ uname -a
    Darwin host 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

**Comment by AlexDenisov** [comment]
Closed via #230
