### ISSUE TITLE
joern-parse.bat: "input line too long" when building classpath

### ISSUE THREAD

**Issue by dgunay** [ShiftLeftSecurity/joern#232]
I ran into problems with the extremely long `APP_CLASSPATH` variable in joern-parse.bat when running joern-cli on Windows. The command was too long and the script would die when trying to set the classpath. I got around it by simply passing a wildcard (`%APP_LIB_DIR%/*`) to the `-cp` argument at the end of the script.

I'd file a PR but I can't find the script in this repo.

**Comment by dgunay** [comment]
ammonite-bridge.bat also has this problem, and the same workaround.

**Comment by fabsx00** [comment]
This one was fixed recently.
