### ISSUE TITLE
Scripts for extracting the dot of ast and cfg

### ISSUE THREAD

**Issue by wubozhi** [ShiftLeftSecurity/joern#248]
could you provide scripts for extracting the dot of ast and cfg from cpg. Many thanks.

**Comment by fabsx00** [comment]
https://github.com/ShiftLeftSecurity/codepropertygraph/pull/724

**Comment by fabsx00** [comment]
For the AST, you can now do `cpg.method.dotAst.l`, or `cpg.method.plotDotAst` to view it.

**Comment by fabsx00** [comment]
For the CFG: https://github.com/ShiftLeftSecurity/codepropertygraph/pull/725
