### ISSUE TITLE
get PDG

### ISSUE THREAD

**Issue by lyqssb** [ShiftLeftSecurity/joern#280]
how can i get PDG from cpg.bin? or just get PDG from source code directly?
thank you !

**Comment by lyqssb** [comment]
joern> loadCpg("nvd.bin") 
res0: Option[Cpg] = Some(io.shiftleft.codepropertygraph.Cpg@24e0bdb)

joern> cpg.runScript("general/pdg.sc") 
cmd1.sc:1: value runScript is not a member of io.shiftleft.codepropertygraph.Cpg
val res1 = cpg.runScript("general/pdg.sc")
               ^
Compilation Failed

how can i fix this?

**Comment by fabsx00** [comment]
Ignore the script and use this: https://github.com/ShiftLeftSecurity/codepropertygraph/pull/882
