### ISSUE TITLE
A bug about the "REACHING_DEF" edge.

### ISSUE THREAD

**Issue by clccc** [ShiftLeftSecurity/joern#310]
Is there a bug about the "REACHING_DEF"edge. For example,
```
int copy = (offset + nbytes > 64 ? 64 - offset : nbytes);
memcpy(pms->buf + offset, p, copy);
```
The query command ```cpg.call.where.(.id == 849111).argument(3).raw.inE("REACHING_DEF").outV.l``` will return ```List[Vertex] = List()```, but the 3rd argument ```copy``` is exactly defined by ```(offset + nbytes > 64 ? 64 - offset : nbytes);```.
I found when the argument's type is "Identifier", the results of query command will be null list.
Is there a better way to get defining chains of a variable?

**Comment by fabsx00** [comment]
Did you run `run.ossDataFlow` first? The data flow edges are not created by default.

**Comment by clccc** [comment]
I did not execute "run.ossDataFlow" first in the past. 
Then I just did it as you say, I got the result as follow: 
------------------------------------------------------------------------------------------------------
joern> cpg.all.size
res161: Int = 458304


joern> run.oss
ossdataflow


def ossdataflow: io.shiftleft.codepropertygraph.Cpg
joern> run.ossdataflow
Overlay dataflowOss already exists - skipping
The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
res162: Cpg = io.shiftleft.codepropertygraph.Cpg@4e99b33


joern> cpg.all.size
res163: Int = 458304


joern> cpg.call.where(_.id == 84911).argument(3).raw.inE("REACHING_DEF").outV.l
res164: List[Vertex] = List()


joern>
--------------------------------------------------------------------------------------------------------
The result still showed the 3rd argument "copy" did not have "REACHING_DEF" edges.


| |
Lin Chen
|
|
cl_softbox@163.com
|
签名由网易邮箱大师定制
On 7/23/2020 15:38，Fabian Yamaguchi<notifications@github.com> wrote：

Did you run run.ossDataFlow first? The data flow edges are not created by default.

**Comment by clccc** [comment]
I did not execute "run.ossDataFlow" first in the past. 
Then I just did it as you say, I got the result as follow: 
------------------------------------------------------------------------------------------------------
joern> cpg.all.size
res161: Int = 458304


joern> run.oss
ossdataflow


def ossdataflow: io.shiftleft.codepropertygraph.Cpg
joern> run.ossdataflow
Overlay dataflowOss already exists - skipping
The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
res162: Cpg = io.shiftleft.codepropertygraph.Cpg@4e99b33


joern> cpg.all.size
res163: Int = 458304


joern> cpg.call.where(_.id == 84911).argument(3).raw.inE("REACHING_DEF").outV.l
res164: List[Vertex] = List()


joern>
--------------------------------------------------------------------------------------------------------
The result still showed the 3rd argument "copy" did not have "REACHING_DEF" edges.




On 7/23/2020 15:38，Fabian Yamaguchi<notifications@github.com> wrote：

Did you run run.ossDataFlow first? The data flow edges are not created by default.

**Comment by clccc** [comment]
Am I wrong? Who can give me some help? The missing REACHING_DEF edges on "Identifier" arguments let my work  getting into trouble.

**Comment by clccc** [comment]
I read the source code of ReachingDefPass(cpg: Cpg) in codepropertygraph. I learned that the REACHING_DEF edge was only between two CFG nodes. So if an argument is a simple variable, it is not a CFG node in the CPG, and there is no REACHING_DEF edges connected the argument.
And now, I have a little request. Could CPG add a "def" key on the REACHING_DEF edge? The "def" key indicate the outV defined the "def" variable which was used in the inV.  Like old joern, the necessary keys of edge can help us qurey information more conveniently !

**Comment by fabsx00** [comment]
Yes, that sounds like the way to go. I'll be implementing this in the coming days. Will keep the issue open until it's done.

**Comment by clccc** [comment]
Great, thanks for your attention. I am looking forward to the fix.




On 8/3/2020 04:11，Fabian Yamaguchi<notifications@github.com> wrote：

Yes, that sounds like the way to go. I'll be implementing this in the coming days. Will keep the issue open until it's done.
