### ISSUE TITLE
A bug about REACHING_DEF

### ISSUE THREAD

**Issue by clccc** [ShiftLeftSecurity/joern#322]
![image](https://user-images.githubusercontent.com/12693134/91371685-3c946600-e844-11ea-9954-a5dbfdda524d.png)

I used the joern-parse command to create CPG. It returned the wrong message showd above. Then I used importCode to create CPG, it is OK. But after then I executed command "run.ossdataflow", joern return the same wrong message. The version of joern is v1.0.179.

**Comment by clccc** [comment]
![image](https://user-images.githubusercontent.com/12693134/91371663-2d151d00-e844-11ea-8490-6580899734a6.png)

**Comment by fabsx00** [comment]
Thanks for the report. I can fix that in a moment.

**Comment by clccc** [comment]
What a quick reply! Thank you for your attention!

**Comment by fabsx00** [comment]
Actually, that's very strange. Can you share the code you are running this on by any chance?

**Comment by clccc** [comment]
The code is zabbix3.4.4.  I did not know which part make it wrong.

**Comment by fabsx00** [comment]
Thanks, I can reproduce it.

**Comment by clccc** [comment]
I rember the old joern can show the file name being parsed when creating cpg. If the new joern give the same info, I can give you more  detail.

**Comment by fabsx00** [comment]
So, that first big is fixed once the change above is in, but I'm seeing another problem when trying to import this code base. Looking into that now as well.

**Comment by fabsx00** [comment]
Actually, looks good. It's just that the function `substitute_simple_macros` is insanely huge and so reaching definition calculation takes quite long. I'd recommend removing that method to speed things up.

**Comment by fabsx00** [comment]
https://github.com/ShiftLeftSecurity/joern/pull/324 - the good news is, it does terminate successfully after about 20 minutes. The bad news is that it spends the majority of time calculating reaching definitions for a single method (`substitude_simple_macros`) on a single core.

**Comment by clccc** [comment]
It is a good result alought the consume time is long. But the reason is the function is too huge. 
I think removing the huge functions  is probabaly not a very good idea . That means user need to adjust their codebase manually before creating CPG with Joern. If we cannot optimize the time problem, I'd rather get up and have a walk.

**Comment by fabsx00** [comment]
Managed to reduce runtime from 20 minutes to 4 minutes on a 10 core workstation by performing some computation in parallel. Cleaning this up, PR will likely come in tonight.

**Comment by clccc** [comment]
I used the latest joern v1.0.183 to create cpg. I found there were none reaching_def edges with a VARIABLE not equal "".  Is there any bug about reaching_def?
![image](https://user-images.githubusercontent.com/12693134/91675076-9f03a400-eb6d-11ea-85fa-5e6c1a6243d7.png)
![image](https://user-images.githubusercontent.com/12693134/91675091-b3e03780-eb6d-11ea-9558-2ae9786aaada.png)
![image](https://user-images.githubusercontent.com/12693134/91675242-3ff25f00-eb6e-11ea-8c6e-44ea963be930.png)
