### ISSUE TITLE
Is still REACHING_DEF...

### ISSUE THREAD

**Issue by clccc** [ShiftLeftSecurity/joern#329]
Two evidence.
1. I used the latest joern v1.0.183 to create cpg. I found there were none reaching_def edges with a VARIABLE not equal "".
![image](https://user-images.githubusercontent.com/12693134/91675076-9f03a400-eb6d-11ea-85fa-5e6c1a6243d7.png)
![image](https://user-images.githubusercontent.com/12693134/91675091-b3e03780-eb6d-11ea-9558-2ae9786aaada.png)
![image](https://user-images.githubusercontent.com/12693134/91675242-3ff25f00-eb6e-11ea-8c6e-44ea963be930.png)

2. I create cpg from the sample code in "DotDdgGeneratorTests"
```
     int foo(int param1, char *param2) {
        int i = 0;
        while(i < 10) {
          char *boo = moo("%d\n", i + bar(i));
          printf(boo);
          i++;
        }
        return 0;
     }
```
Then, I plot the ddg with command "cpg.method.wherer(_.id == 1000102).plotDotDdg", and return the graph belowed. In the Ddg, there is not any reaching_def edges labled VARIABLE, which is different from your ddg in https://github.com/ShiftLeftSecurity/codepropertygraph/pull/882
 
![image](https://user-images.githubusercontent.com/12693134/91696824-bf9a2100-eba2-11ea-984f-4d8b8391e064.png)

I print all reaching-def edges' variable.
![image](https://user-images.githubusercontent.com/12693134/91697224-54048380-eba3-11ea-8f64-ba119cc5134d.png)

**Comment by fabsx00** [comment]
Ah, thanks for the bug report. Must have broken this a few commits ago. I'll look into it today.

**Comment by fabsx00** [comment]
Found and fixed the bug: https://github.com/ShiftLeftSecurity/codepropertygraph/pull/925 - thanks for reporting. Also added a test.

**Comment by fabsx00** [comment]
Fixed in 1.0.184.

**Comment by fabsx00** [comment]
https://github.com/ShiftLeftSecurity/joern/pull/330

**Comment by clccc** [comment]
Thanks for your quick response and great work!

**Comment by fabsx00** [comment]
No problem. Let me know if you find more issues, this code is relatively new.

**Comment by clccc** [comment]
ok, It is my pleasure.
