### ISSUE TITLE
Empty PDG 

### ISSUE THREAD

**Issue by brutalsavage** [ShiftLeftSecurity/joern#342]
using `graph/graph-for-funcs.sc` and for all functions the pdg section is empty.

using `pdg-for-funcs-dumps.sc` gives empty results for all functions as well.

**Comment by fabsx00** [comment]
That script doesn't work, yes. I'll provide a replacement some time this week.

**Comment by fabsx00** [comment]
https://github.com/ShiftLeftSecurity/codepropertygraph/pull/973

**Comment by fabsx00** [comment]
Duplicate of https://github.com/ShiftLeftSecurity/codepropertygraph/issues/802
