### ISSUE TITLE
Quickstart examples are broken

### ISSUE THREAD

**Issue by m1cm1c** [ShiftLeftSecurity/joern#386]
Joern's quickstart (https://docs.joern.io/quickstart) contains this command:

    cpg.call.filter(_.argument.code("stderr")).l

Upon execution in the current version of Joern, this is printed:

```
cmd1.sc:1: missing argument list for method argument in class CallMethods
Unapplied methods are only converted to functions when a function type is expected.
You can make this conversion explicit by writing `argument _` or `argument(_)` instead of `argument`.
val res1 = cpg.call.filter(_.argument.code("stderr")).l
                             ^
Compilation Failed
```

Both

    cpg.call.filter(_.code.contains("stderr")).l

and

    cpg.call.filter(thing => thing.code.contains("stderr")).l

work and produce the output displayed in the quickstart. But I don't know how to get the "only select those calls which have connections to nodes of type ARGUMENT" part right.

**Comment by fabsx00** [comment]
I think it should be `cpg.call.where(_.argument.code("stderr")).l`. Can you check?

**Comment by fabsx00** [comment]
Fixed by https://github.com/joernio/website/pull/5

**Comment by m1cm1c** [comment]
Yes, it works. Thank you! :)
