### ISSUE TITLE
joern can not build cpg any more

### ISSUE THREAD

**Issue by xiaoxiong007** [ShiftLeftSecurity/joern#387]
Hi,When I use joern to work, I find a info:
'Creating project `x42-c` for code at `./x42/c`
Support for this language is only available in ShiftLeft Ocular with an appropriate license
res1: Option[Cpg] = None'. 

is it ocular that charges

**Comment by fabsx00** [comment]
Can you post exactly what you're executing? That error indicates that joern thinks that this isn't a C project. Don't worry, Joern continue to support C/C++, free of charge.

**Comment by ursachec** [comment]
@xiaoxiong007 The latest install script for Joern has an issue that still needs to be fixed.
To move forward in the meantime, I recommend you download the zip file from the releases and start Joern from there https://github.com/ShiftLeftSecurity/joern/releases/download/v1.1.43/joern-cli.zip. Your `importCode` command should work without issues.

**Comment by colorlight** [comment]
Same problem, I have tried v1.1.43, it still doesn't work
