### ISSUE TITLE
Will joern support another program language in the future? like java

### ISSUE THREAD

**Issue by Zddd97** [ShiftLeftSecurity/joern#409]
[fabs: sorry, instead of replying, I accidentally edited your original message and don't know what it was. I didn't know that was possible...]

**Comment by fabsx00** [comment]
Well, in fact, it already does, but the support is very very alpha at the moment. Try out:
joern-parse --language java <your-java-archive.jar>. There are a few more languages that are under development right now, to be released in early 2021.

**Comment by Zddd97** [comment]
> Well, in fact, it already does, but the support is very very alpha at the moment. Try out:
> joern-parse --language java <your-java-archive.jar>. There are a few more languages that are under development right now, to be released in early 2021.

Will these program languages released in 2021 also support the generation of cpg？Thanks

**Comment by fabsx00** [comment]
Yes
