### ISSUE TITLE
Incorrect type for first identifier declaration.

### ISSUE THREAD

**Issue by hemantabhagat** [ShiftLeftSecurity/joern#41]
I have a simple test code
```
#ifndef FUNCTIONS_H
#define FUNCTIONS_H

void call_function();
int glob;

#endif // FUNCTIONS_H
````

When I generate the CPG and query database for DECLARES relationship, I get type 

> **define FUNCTIONS_H void ( )**

 of declaration call_function. as shown
![image](https://user-images.githubusercontent.com/17696572/57523046-8dc3d200-7341-11e9-84a7-63bec845ee8a.png)

Whereas, The type for next variable glob is correct.

**Comment by fabsx00** [comment]
Could it be that you're using `https://github.com/octopus-platform/joern` (discontinued end of 2016)? We don't have `DECLARES` edges and it looks like you're using neo4j - which is what that prior version did. Nonetheless, let me see if that parser error exists with this version as well.

**Comment by hemantabhagat** [comment]
I followed [this guide](https://joern.readthedocs.io/en/latest/installation.html) for setup.

**Comment by fabsx00** [comment]
Added failing test here: https://github.com/ShiftLeftSecurity/fuzzyc2cpg/tree/fabs/preproctest - we seem to have ported that problem over.

**Comment by fabsx00** [comment]
Thanks for reporting this, here's the fix: https://github.com/ShiftLeftSecurity/fuzzyc2cpg/pull/57
Please use the new version of joern at https://joern.io
I'll make sure to get of that old documentation one of these days.

**Comment by hemantabhagat** [comment]
Thank you very much for such a prompt response!
