### ISSUE TITLE
Joern does NOT work with .cpp files

### ISSUE THREAD

**Issue by muoitranduc** [ShiftLeftSecurity/joern#487]
I followed the installation instructions on the Github page. 
Strangely, joern on both of my Macbook and Ubuntu machines doesn't work with .cpp files while it works perfectly fine with .c files. 

This is the content of test.c file:

> muoi@Muois-MacBook-Pro test % cat test.c 
> void foo() {
>   int x = source();
>   if (x < MAX) {
>     int y = 2 * x;
>     sink(y);
>   }
> }

Joern's log:

> importCode(inputPath="/Users/muoi/test", projectName="test") 
> Using generator for language: C
> Creating project `test` for code at `/Users/muoi/test`
> moving cpg.bin.zip to cpg.bin because it is already a database file
> Creating working copy of CPG to be safe
> Loading base CPG from: /Users/muoi/workspace/test/cpg.bin.tmp
> Adding default overlays to base CPG
> 2021-03-15 17:12:28.000 WARN Linker: Could not create edge. Destination lookup failed. edgeType=EVAL_TYPE, srcNodeType=CALL, srcNodeId=1000104, dstNodeType=TYPE, dstFullName=
> 2021-03-15 17:12:28.001 WARN Linker: Could not create edge. Destination lookup failed. edgeType=EVAL_TYPE, srcNodeType=CALL, srcNodeId=1000106, dstNodeType=TYPE, dstFullName=
> 2021-03-15 17:12:28.001 WARN Linker: Could not create edge. Destination lookup failed. edgeType=EVAL_TYPE, srcNodeType=CALL, srcNodeId=1000108, dstNodeType=TYPE, dstFullName=
> 2021-03-15 17:12:28.001 WARN Linker: Could not create edge. Destination lookup failed. edgeType=EVAL_TYPE, srcNodeType=CALL, srcNodeId=1000113, dstNodeType=TYPE, dstFullName=
> 2021-03-15 17:12:28.001 WARN Linker: Could not create edge. Destination lookup failed. edgeType=EVAL_TYPE, srcNodeType=CALL, srcNodeId=1000115, dstNodeType=TYPE, dstFullName=
> 2021-03-15 17:12:28.002 WARN Linker: Could not create edge. Destination lookup failed. edgeType=EVAL_TYPE, srcNodeType=CALL, srcNodeId=1000118, dstNodeType=TYPE, dstFullName=
> The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
> Code successfully imported. You can now query it using `cpg`.
> For an overview of all imported code, type `workspace`.
> res7: Option[Cpg] = Some(value = io.shiftleft.codepropertygraph.Cpg@6a1eef38)
> 
> joern> cpg.method.name("foo").dotCfg.l 
> res8: List[String] = List(
>   """digraph foo {  
> "1000104" [label = "(<operator>.assignment,x = source())" ]
> "1000106" [label = "(source,source())" ]
> "1000108" [label = "(<operator>.lessThan,x < MAX)" ]
> "1000113" [label = "(<operator>.assignment,y = 2 * x)" ]
> "1000115" [label = "(<operator>.multiplication,2 * x)" ]
> "1000118" [label = "(sink,sink(y))" ]
> "1000101" [label = "(METHOD,foo)" ]
> "1000120" [label = "(METHOD_RETURN,void)" ]
>   "1000104" -> "1000108" 
>   "1000106" -> "1000104" 
>   "1000108" -> "1000120" 
>   "1000108" -> "1000115" 
>   "1000113" -> "1000118" 
>   "1000115" -> "1000113" 
>   "1000118" -> "1000120" 
>   "1000101" -> "1000106" 
> }
> """
> )

But when I change test.c into test.cpp:

> muoi@Muois-MacBook-Pro test % mv test.c test.cpp

Joern does NOT work anymore:

> joern> importCode(inputPath="/Users/muoi/test", projectName="test") 
> Using generator for language: C
> Creating project `test` for code at `/Users/muoi/test`
> Project with name test already exists - overwriting
> Turning working copy into new persistent CPG
> moving cpg.bin.zip to cpg.bin because it is already a database file
> Creating working copy of CPG to be safe
> Loading base CPG from: /Users/muoi/workspace/test/cpg.bin.tmp
> Adding default overlays to base CPG
> The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
> Code successfully imported. You can now query it using `cpg`.
> For an overview of all imported code, type `workspace`.
> res9: Option[Cpg] = Some(value = io.shiftleft.codepropertygraph.Cpg@fd42b93)
> 
> joern> cpg.method.name("foo").dotCfg.l 
> res10: List[String] = List()

Does anyone know how to fix this?

**Comment by maximzubkov** [comment]
Hello, @muoitranduc! Seems like I have found a solution to the problem, you can check the ([issue](https://github.com/ShiftLeftSecurity/codepropertygraph/issues/1163))

**Comment by itsacoderepo** [comment]
@muoitranduc The issue is fixed in the current version.
