### ISSUE TITLE
About ImportCode("xx.jar") can't use

### ISSUE THREAD

**Issue by LinShiG0ng** [ShiftLeftSecurity/joern#518]
I was download and unzip joern-cli.zip

Open joern in the joern-cli directory then use  ImportCode("xx.jar") will stuck here ![image](https://user-images.githubusercontent.com/66135346/114895323-00992a00-9e42-11eb-9152-4e9c19b93746.png)![image](https://user-images.githubusercontent.com/66135346/114892694-97181c00-9e3f-11eb-85d9-3663e9c7071c.png)

Open joern in other directory  then use ImportCode("xx.jar") Tips are as follows No Java language frontend present
![image](https://user-images.githubusercontent.com/66135346/114895421-127acd00-9e42-11eb-96d3-fa27da864163.png)

but joern-parse it's work
![image](https://user-images.githubusercontent.com/66135346/114895960-8026f900-9e42-11eb-802f-91e4bff43503.png)

my virtual machine environment 
![image](https://user-images.githubusercontent.com/66135346/114896754-2d9a0c80-9e43-11eb-890c-d6e1e490b2a5.png)

**Comment by prabhu** [comment]
[hsl-joern.txt](https://github.com/ShiftLeftSecurity/joern/files/6337960/hsl-joern.txt)

Debug log for hsl

**Comment by itsacoderepo** [comment]
Fixed with 1.1.160 release (https://github.com/ShiftLeftSecurity/joern/releases/tag/v1.1.160)
