### ISSUE TITLE
How to transfer the python program from the old joern  to the shiftleft-joern quickly?

### ISSUE THREAD

**Issue by clccc** [ShiftLeftSecurity/joern#56]
I have wrote  some python programs running on the old Joern framework, they have some bugs but hard to debug because of REST. So I want to rewrite them with the new Joern. 
The new version is more powerful and complicated from the old one. I want to know is the Joern completed basically? Is it the right time to start the rewrite work now?  
When I learned the new version, I felt the documentation and samples are bit sparse. Although I have used the old Joern, but I felt difficult to understand the schema of the new Joern clearly.  Would you provide more detailed documentation.
 I'm eager to experience the power of the shiftleft-joern. 
Thanks for the great work very very much! 
@fabsx00 @mpollmeier @ml86 @

**Comment by fabsx00** [comment]
Hey @clccc. Thanks for the flowers! I just implemented a new version of python-joern and merged it. Documentation is coming up, but you can already check out the following python wheel:
https://github.com/ShiftLeftSecurity/codepropertygraph/tree/master/cpgclientlib

**Comment by fabsx00** [comment]
To answer your question about the state of new Joern: we're mostly working on documentation and interfacing at this point. Official announcement of a first complete version is planned for mid June.

**Comment by clccc** [comment]
Thank you for your prompt reply! I had a familiar feeling when I read the code of cpgclientlib. It feels great for regular users. But I have a little wary of the querying speed used client/server communication. Because my program always spend 3~5 hours to return a result. Of course, it could also be that my algorithm is not good enough.  Will the joern support for local querying? In my opinion, the local querying way is better to debug also. And the new joern will support scala or python? Maybe I should do some preparation. Please forgive my unfamiliarity with the new joern now. 
Finally, I am happy to know the news about the documentation and the first complete version. Thanks very much!
