### ISSUE TITLE
Real bug queries

### ISSUE THREAD

**Issue by Smaugon** [ShiftLeftSecurity/joern#67]
Hi Fabian, thx for your outstanding work.

I have used the joern for C/C++ for several weeks and read the documents, but I cannot find examples for the types of vulnerabilies in the paper. Wonder why u did not push them on the github. Hope u could show them to more developers.

Thank you!

**Comment by fabsx00** [comment]
Sample queries are being added here and here:
https://github.com/ShiftLeftSecurity/codepropertygraph/tree/master/semanticcpg/src/test/scala/io/shiftleft/semanticcpg/samplequeries
https://github.com/ShiftLeftSecurity/codepropertygraph/tree/master/dataflowengine/src/test/scala/io/shiftleft/dataflowengine/samplequeries
Enjoy.

**Comment by fabsx00** [comment]
https://github.com/ShiftLeftSecurity/codepropertygraph/pull/473

**Comment by fabsx00** [comment]
https://github.com/ShiftLeftSecurity/codepropertygraph/pull/480

**Comment by Smaugon** [comment]
It's a pity that I have to quit my work on joern, still I appreciate that u can show them.
Thx for joern, Good luck to u.
