### ISSUE TITLE
COLUMN_NUMBER_END and LINE_NUMBER_END not supported. 

### ISSUE THREAD

**Issue by turnersr** [ShiftLeftSecurity/joern#82]
According to the schema described in https://github.com/ShiftLeftSecurity/codepropertygraph/blob/master/codepropertygraph/src/main/resources/schemas/base.json . Some nodes should have `COLUMN_NUMBER_END` and `LINE_NUMBER_END` values, but joern doesn't appear to be following the schema and will not provide `COLUMN_NUMBER_END` and `LINE_NUMBER_END`. Maybe I am not looking in the right spot? 

Thanks!

**Comment by fabsx00** [comment]
Thanks, yes, need to fix that in the fuzzyc frontend. Not all fields are filled out by that frontend at the moment.
