### ISSUE TITLE
Pulling Out Code Like In Old Joern

### ISSUE THREAD

**Issue by turnersr** [ShiftLeftSecurity/joern#85]
I noticed that LINE_NUMBER_END and COLUMN_NUMBER_END  were recently removed from the base schema. 

Does this mean users will no longer be able to extract code like the older version of joern supported?  In the past you could do the following:

```
echo "getFunctionsByParameter('*len*').id" | joern-lookup -g | joern-location | joern-code > dump.c
```

**Comment by fabsx00** [comment]
Good point. I think we should revisit storage of end indices or markers of some kind for source-based frontends in the very near future. The field was removed for now as no frontend fills it out and it just cost us space.

**Comment by turnersr** [comment]
Ok, i really liked this feature. It was super useful. Thanks for considering supporting this use case like you all used to.
