### ISSUE TITLE
Argument tainting

### ISSUE THREAD

**Issue by FilippoRezzonico** [ShiftLeftSecurity/joern#9]
Hi! 
I started to look at this new version of Joern and did some experiments with simple C code:
#include <stdio.h>
#include <string.h>
    int main(int argc, char **argv)
    {
        char str[80];
        strcpy(str, argv[1]);
        printf(str);
        return 0;
    }
I wrote the following in my main.scala:
    val arg = cpg.call.name("printf").filter(call => call.argument.code("str")).argument
    val result = arg.reachableByFlows(cpg.identifier).p
    result.toStream.foreach(x => print(x + "\n"))
I was expecting to get a path from "printf(str)" to the second argument of the main function but without tainting the arguments like I read in the older Joern version I don't think it is possible.
Instead I only got:
 | tracked    | lineNumber| method| file                |
 |======================================================|
 | printf(str)| 7         | main  | tests/mytest/free1.c|

Is still possible to taint arguments with this version of Joern? If so, can you give me some hints on how to do so? Thanks!

**Comment by fabsx00** [comment]
This brings in the necessary feature. @b-64rry will explain in more detail.
https://github.com/ShiftLeftSecurity/codepropertygraph/pull/133

**Comment by FilippoRezzonico** [comment]
I will wait for the documentation update then! Thanks a lot!
